# Generated by Django 5.1.5 on 2025-01-26 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('color', models.CharField(max_length=50)),
                ('weight', models.PositiveSmallIntegerField()),
                ('photos', models.ImageField(upload_to='pets/')),
            ],
        ),
        migrations.CreateModel(
            name='PetAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=75)),
                ('adoption_fee', models.DecimalField(decimal_places=2, max_digits=13)),
                ('availability', models.CharField(choices=[('A', 'Available'), ('R', 'Reserved')], max_length=1)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petcenter.pet')),
            ],
        ),
        migrations.CreateModel(
            name='PetBehaviour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperament', models.CharField(max_length=75)),
                ('activity_level', models.CharField(choices=[('HIGH', 'High'), ('MODERATE', 'Moderate'), ('LOW', 'Low')], max_length=20)),
                ('compatibility', models.CharField(max_length=75)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petcenter.pet')),
            ],
        ),
        migrations.CreateModel(
            name='PetHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccinated', models.BooleanField(default=False)),
                ('neutered', models.BooleanField(default=False)),
                ('dewormed', models.BooleanField(default=False)),
                ('special_needs', models.CharField(blank=True, max_length=250, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petcenter.pet')),
            ],
        ),
    ]
